export const PRODUCTS = [
  { id: 1, name: "Ultimate Business Planner 2026", category: "Planners", price: 6, image: "📊", description: "Comprehensive business planning template with financial projections and goal tracking." },
  { id: 2, name: "Social Media Content Calendar", category: "Marketing", price: 6, image: "📅", description: "12-month social media calendar with content ideas and posting schedules." },
  { id: 3, name: "Meal Prep Guide & Recipes", category: "Health", price: 6, image: "🥗", description: "30-day meal prep plan with 50+ healthy recipes and shopping lists." },
  { id: 4, name: "Resume & CV Templates Pack", category: "Career", price: 6, image: "📄", description: "20 professional resume templates in multiple formats." },
  { id: 5, name: "Budget Tracker & Financial Planner", category: "Finance", price: 6, image: "💰", description: "Personal finance spreadsheet with budget categories and savings goals." },
  { id: 6, name: "Fitness & Workout Plan", category: "Health", price: 6, image: "💪", description: "12-week fitness program with exercise videos and meal guidance." },
  { id: 7, name: "Wedding Planning Checklist", category: "Events", price: 6, image: "💒", description: "Complete wedding planning timeline from engagement to honeymoon." },
  { id: 8, name: "Small Business Invoice Templates", category: "Business", price: 6, image: "🧾", description: "Professional invoice templates for freelancers and small businesses." },
  { id: 9, name: "Garden Planning & Plant Guide", category: "Home", price: 6, image: "🌱", description: "Vegetable garden planner with seasonal planting schedules." },
  { id: 10, name: "Kids Activity Pack", category: "Family", price: 6, image: "🎨", description: "100+ educational activities and printable crafts for children." },
  { id: 11, name: "Travel Itinerary Planner", category: "Travel", price: 6, image: "✈️", description: "Trip planning template with budget tracker and packing lists." },
  { id: 12, name: "Podcast Launch Kit", category: "Media", price: 6, image: "🎙️", description: "Complete guide to starting your own podcast with equipment list." },
  { id: 13, name: "Etsy Shop Starter Guide", category: "Business", price: 6, image: "🛍️", description: "Step-by-step guide to setting up a profitable Etsy shop." },
  { id: 14, name: "Daily Routine Planner", category: "Productivity", price: 6, image: "✅", description: "Morning and evening routine templates for maximum productivity." },
  { id: 15, name: "Recipe Cookbook Collection", category: "Food", price: 6, image: "👨‍🍳", description: "100 family-favorite recipes with beautiful photo templates." },
  { id: 16, name: "Password Manager Template", category: "Tech", price: 6, image: "🔐", description: "Secure password tracking spreadsheet with encryption tips." },
  { id: 17, name: "Habit Tracker & Goal Setting", category: "Self-Improvement", price: 6, image: "🎯", description: "66-day habit tracking system with accountability charts." },
  { id: 18, name: "Blog Post Templates", category: "Content", price: 6, image: "✍️", description: "50 blog post templates for various niches and topics." },
  { id: 19, name: "Home Organization System", category: "Home", price: 6, image: "🏠", description: "KonMari-style organization guides and room-by-room checklists." },
  { id: 20, name: "Stock Market Investment Guide", category: "Finance", price: 6, image: "📈", description: "Beginner's guide to investing with portfolio templates." },
  { id: 21, name: "YouTube Channel Templates", category: "Media", price: 6, image: "▶️", description: "Thumbnails, banners, and intro templates for YouTubers." },
  { id: 22, name: "Meditation & Mindfulness Guide", category: "Wellness", price: 6, image: "🧘", description: "30-day meditation journey with audio scripts and logs." },
  { id: 23, name: "Party Planning Checklist", category: "Events", price: 6, image: "🎉", description: "Ultimate party planning system for any celebration." },
  { id: 24, name: "Freelancer Contract Templates", category: "Business", price: 6, image: "📝", description: "Legal contract templates for freelance professionals." },
  { id: 25, name: "Baby Milestone Tracker", category: "Family", price: 6, image: "👶", description: "Photo props and milestone checklists for baby's first year." },
  { id: 26, name: "Real Estate Investment Calculator", category: "Finance", price: 6, image: "🏢", description: "Property investment analysis tools and rental income templates." },
  { id: 27, name: "Color Palette Design System", category: "Design", price: 6, image: "🎨", description: "Professional brand color palette generator and guide." },
  { id: 28, name: "Sleep Schedule Planner", category: "Health", price: 6, image: "😴", description: "Sleep improvement program with bedtime routine templates." },
  { id: 29, name: "Course Creation Workbook", category: "Education", price: 6, image: "📚", description: "Step-by-step guide to creating your first online course." },
  { id: 30, name: "Pet Care & Training Guide", category: "Pets", price: 6, image: "🐕", description: "Comprehensive dog training manual with care schedules." },
  { id: 31, name: "Project Management Templates", category: "Business", price: 6, image: "📋", description: "Gantt charts, Kanban boards, and milestone trackers." },
  { id: 32, name: "Tax Preparation Checklist", category: "Finance", price: 6, image: "🧾", description: "Year-round tax organization system for individuals." },
  { id: 33, name: "Book Club Reading Tracker", category: "Lifestyle", price: 6, image: "📖", description: "Reading list organizer with discussion questions." },
  { id: 34, name: "Newsletter Template Pack", category: "Marketing", price: 6, image: "📧", description: "Email newsletter templates with design assets." },
  { id: 35, name: "Minimalist Living Guide", category: "Lifestyle", price: 6, image: "🌿", description: "Decluttering and minimalism workbook with action steps." },
  { id: 36, name: "Birthday Party Games Pack", category: "Family", price: 6, image: "🎈", description: "20 party games for kids with instructions and printables." },
  { id: 37, name: "Customer Service Scripts", category: "Business", price: 6, image: "💬", description: "Professional scripts for handling customer inquiries." },
  { id: 38, name: "Plant-Based Diet Meal Plan", category: "Health", price: 6, image: "🥬", description: "4-week vegan meal plan with 80+ recipes." },
  { id: 39, name: "Office Chair Yoga Guide", category: "Health", price: 6, image: "🪑", description: "15-minute desk stretches and yoga poses for office workers." },
  { id: 40, name: "Product Launch Checklist", category: "Business", price: 6, image: "🚀", description: "Pre-launch checklist and marketing timeline template." },
  { id: 41, name: "Gift Giving Guide", category: "Lifestyle", price: 6, image: "🎁", description: "Gift idea organizer for all occasions and budgets." },
  { id: 42, name: "Affiliate Marketing Blueprint", category: "Marketing", price: 6, image: "💻", description: "Complete guide to building passive income online." },
  { id: 43, name: "Weekly Cleaning Schedule", category: "Home", price: 6, image: "🧹", description: "Room-by-room cleaning checklist with timer guides." },
  { id: 44, name: "Photography Shot List", category: "Media", price: 6, image: "📷", description: "500+ photo ideas organized by theme and location." },
  { id: 45, name: "Retirement Planning Workbook", category: "Finance", price: 6, image: "🏖️", description: "Retirement savings calculator and lifestyle planning guide." },
  { id: 46, name: "Podcast Guest Pitch Template", category: "Media", price: 6, image: "📨", description: "Email templates for booking podcast appearances." },
  { id: 47, name: "Pantry Organization System", category: "Home", price: 6, image: "🥫", description: "Pantry makeover guide with label templates." },
  { id: 48, name: "Side Hustle Action Plan", category: "Business", price: 6, image: "💼", description: "30-day plan to start your profitable side hustle." },
  { id: 49, name: "Gardening Journal", category: "Home", price: 6, image: "🌻", description: "Seasonal garden planner with plant profiles and日志." },
  { id: 50, name: "Self-Care Starter Kit", category: "Wellness", price: 6, image: "💆", description: "50 self-care activities with weekly planner and tracker." },
];

export const CATEGORIES = [
  "All",
  "Business",
  "Finance",
  "Health",
  "Marketing",
  "Media",
  "Lifestyle",
  "Home",
  "Family",
  "Career",
  "Productivity",
  "Wellness",
  "Events",
  "Food",
  "Tech",
  "Self-Improvement",
  "Content",
  "Travel",
  "Pets",
  "Design",
  "Education",
];

export const PRICE = 6;
